/** All user-facing text. The app is in English (AGENTS.md). */
export const copy = {
  brand: {
    name: 'Interview Deck',
    wordmark: 'Interview Deck',
    tagline: 'Pick a card. Answer out loud. Get better.',
    premium: 'Premium',
  },
  menu: {
    label: 'Menu',
    about: 'About',
    community: 'Community on Skool',
  },
  home: {
    coverTitle: 'Pick a card.',
    coverSubtitle: 'Answer out loud.',
    tapToDraw: 'Tap to draw',
    drawLabel: 'Draw a card from the deck',
    shuffle: 'Shuffle & draw',
    startMock: 'Start mock interview',
    decks: 'Decks',
    mode: 'Mode',
    modes: { practice: 'Free practice', mock: 'Mock interview' },
    mockDescription: 'A focused 15-minute interview preparation session.',
    cards: (count: number) => `${count} cards`,
  },
  card: {
    close: 'Back to the deck',
    next: 'Next card',
    previous: 'Previous card',
    counter: (position: number, total: number) => `${position} of ${total}`,
    stages: { 'opening': 'Warm-up', 'intro': 'Intro', 'follow-up': 'Follow-up', 'closing': 'Wrap-up' },
    hint: 'Hint',
    example: 'See an example answer',
    exampleNote: 'Use it as a model, not a script. Your own story always works better.',
    audio: {
      voiceLabel: 'Question voice',
      play: 'Play question',
      stop: 'Pause question',
      voices: { female: 'Female voice', male: 'Male voice', off: 'No audio' },
    },
    wordmark: 'Interview Deck',
    recorder: {
      label: 'Record your answer',
      start: 'Record your answer',
      stop: 'Stop recording',
      save: 'Save video',
      discard: 'Discard video',
      error: 'Could not open the camera. Check the browser permission and try again.',
      privacy: 'The video stays on your device.',
      brand: 'Interview Deck · by Trampar na Gringa',
    },
    timer: {
      waiting: 'Listen to the question',
      startingIn: (seconds: number) => `Starting in ${seconds}…`,
      speakNow: 'Speak now',
      paused: 'Paused',
      timeUp: 'Time is up',
      startNow: 'Start the timer now',
      pause: 'Pause timer',
      resume: 'Resume timer',
      restart: 'Restart timer',
      remaining: (time: string) => `${time} remaining`,
    },
    notFound: 'This deck does not exist.',
  },
  mockComplete: {
    title: 'That\'s the interview.',
    body: (count: number) => `You answered ${count} questions, from the small talk to the closing. Real interviews feel a lot like this.`,
    again: 'Start another mock interview',
    back: 'Back to the decks',
  },
  cta: {
    home: { lead: 'Go further with Premium:', body: ' hints, mock interviews and live practice.' },
    card: { lead: 'Not sure how to answer?', body: ' Get hints and mock interviews with Premium.' },
    live: { lead: 'Practice with people:', body: ' join a live practice room on Skool.' },
  },
  about: {
    title: 'About',
    body: [
      'Interview Deck helps you practice job interviews out loud. Pick a card, answer it like you would in a real interview, and move on to the next one.',
      'Every session follows a real interview: a bit of small talk, the introduction, the questions of your deck and the closing.',
      'Premium members get hints on every card, full mock interviews and live practice rooms with other people.',
    ],
    madeBy: 'Made by Trampar na Gringa.',
    back: 'Back to the deck',
  },
  errors: {
    notFound: 'Page not found',
    generic: 'Something went wrong',
    home: 'Back to the deck',
  },
} as const
