-- Generated by scripts/build-seed.ts from supabase/seed/decks/*.json. Do not edit.

insert into public.decks (slug, name, short_name, tagline, color, is_free, sort) values ('general', 'General Deck', 'General', 'Start here', 'general', true, 0)
  on conflict (slug) do update set name = excluded.name, short_name = excluded.short_name, tagline = excluded.tagline, color = excluded.color, is_free = excluded.is_free, sort = excluded.sort;

insert into public.cards (deck_slug, number, category, question, hint) values
  ('general', 1, 'Tell me about yourself', 'Tell me about yourself.', 'Present, past, future: what you do now, one or two proof points that got you here, and why this role is the next step. Keep it under two minutes.'),
  ('general', 2, 'Motivation', 'Why do you want to work here?', 'Connect something specific about the company (product, mission, team) to something specific about you. Avoid generic praise.'),
  ('general', 3, 'Motivation', 'Why are you looking for a new role?', 'Stay positive and forward-looking: what you want to grow into, not what you are running from.'),
  ('general', 4, 'Strengths & Weaknesses', 'What is your greatest strength?', 'Pick one strength that matters for this role and prove it with a short, concrete example and its result.'),
  ('general', 5, 'Strengths & Weaknesses', 'What is a weakness you are working on?', 'Name a real but non-critical weakness, then show what you are doing about it and the progress so far.'),
  ('general', 6, 'Behavioral', 'Tell me about a time you disagreed with someone on your team.', 'Use STAR: Situation, Task, Action, Result. Focus on how you handled it, not who was right.'),
  ('general', 7, 'Behavioral', 'Tell me about a time you failed.', 'Own the mistake in one sentence, spend most of the time on what you learned and what you do differently now.'),
  ('general', 8, 'Behavioral', 'Tell me about a project you are proud of.', 'Explain the goal, your specific part (say "I", not "we"), and a measurable result.'),
  ('general', 9, 'Behavioral', 'Describe a time you had to meet a tight deadline.', 'Show how you prioritized and communicated trade-offs, not just that you worked late.'),
  ('general', 10, 'Behavioral', 'Tell me about a time you received difficult feedback.', 'Show that you listened, what you changed, and how you know the change worked.'),
  ('general', 11, 'Career', 'Where do you see yourself in five years?', 'Show ambition that fits the company: the skills and scope you want to grow into, not a job title.'),
  ('general', 12, 'Career', 'Walk me through your resume.', 'Tell it as a story with a thread. One sentence per step, more detail on the most recent and relevant role.'),
  ('general', 13, 'Career', 'What are you looking for in your next role?', 'Name two or three concrete things (scope, team, problems) and tie them to this role.'),
  ('general', 14, 'Motivation', 'What do you know about our company?', 'Show you did your homework: product, customers, a recent change. Then one sentence on why it matters to you.'),
  ('general', 15, 'Leadership', 'Tell me about a time you took the lead without being asked.', 'Explain the gap you noticed, why it mattered, what you did and what changed because of it.'),
  ('general', 16, 'Behavioral', 'Describe a situation where you had to learn something quickly.', 'Explain your learning approach (sources, people, practice) and the result, not only that you learned it.'),
  ('general', 17, 'Behavioral', 'Tell me about a time you worked with someone from a different culture.', 'Show curiosity and adaptation: what was different, what you adjusted, and the outcome for the work.'),
  ('general', 18, 'Strengths & Weaknesses', 'How would your colleagues describe you?', 'Pick two or three traits and back each one with a quick example or something a colleague actually said.'),
  ('general', 19, 'Career', 'Why should we hire you?', 'Summarize the match: their top needs, your matching proof points, and what you would bring in the first months.'),
  ('general', 20, 'Motivation', 'Do you have any questions for us?', 'Always say yes. Ask about the team''s challenges, how success is measured, or what the first 90 days look like.')
  on conflict (deck_slug, number) do update set category = excluded.category, question = excluded.question, hint = excluded.hint;
delete from public.cards where deck_slug = 'general' and number > 20;

insert into public.decks (slug, name, short_name, tagline, color, is_free, sort) values ('behavioral', 'Behavioral Deck', 'Behavioral', 'STAR stories', 'behavioral', false, 1)
  on conflict (slug) do update set name = excluded.name, short_name = excluded.short_name, tagline = excluded.tagline, color = excluded.color, is_free = excluded.is_free, sort = excluded.sort;

insert into public.cards (deck_slug, number, category, question, hint) values
  ('behavioral', 1, 'Conflict', 'Tell me about a time you had a conflict with your manager.', 'STAR. Show respect for their position, how you raised your view with data, and how you moved forward together.'),
  ('behavioral', 2, 'Conflict', 'Describe a time you had to work with a difficult stakeholder.', 'Explain what they cared about, how you adapted your communication, and the result for the project.'),
  ('behavioral', 3, 'Ownership', 'Tell me about a time you went beyond your responsibilities.', 'Make the extra step clear: what was expected, what you did on top, and the impact.'),
  ('behavioral', 4, 'Ownership', 'Describe a mistake you made that affected others.', 'Own it early, explain how you fixed it and communicated, then the process you changed so it does not happen again.'),
  ('behavioral', 5, 'Prioritization', 'Tell me about a time you had too many priorities at once.', 'Show your criteria (impact, urgency, dependencies) and how you aligned with others on what to drop.'),
  ('behavioral', 6, 'Influence', 'Tell me about a time you convinced others to adopt your idea.', 'Show how you understood their concerns and used evidence, not only persistence.'),
  ('behavioral', 7, 'Influence', 'Describe a time you had to say no to someone.', 'Explain the reason, how you said it, and what alternative you offered.'),
  ('behavioral', 8, 'Adaptability', 'Tell me about a time a project changed direction halfway through.', 'Show how you reacted, what you salvaged, and how you kept the team moving.'),
  ('behavioral', 9, 'Adaptability', 'Describe a time you worked with incomplete information.', 'Explain the assumptions you made, how you reduced risk, and how you validated along the way.'),
  ('behavioral', 10, 'Teamwork', 'Tell me about a time you helped a struggling teammate.', 'Focus on what you noticed, how you offered help without taking over, and how they did afterwards.'),
  ('behavioral', 11, 'Teamwork', 'Describe your best experience working in a team.', 'Name what made it work (roles, communication, trust) and your specific contribution.'),
  ('behavioral', 12, 'Results', 'Tell me about your biggest professional achievement.', 'Give context on why it was hard, your specific actions, and a number that shows the result.'),
  ('behavioral', 13, 'Results', 'Tell me about a goal you did not reach.', 'Be honest about the gap, what you learned, and how you applied it to the next goal.'),
  ('behavioral', 14, 'Communication', 'Describe a time you had to explain something complex to a non-expert.', 'Show how you checked what they already knew and used an analogy or example to bridge the gap.'),
  ('behavioral', 15, 'Communication', 'Tell me about a time you had to deliver bad news.', 'Explain timing, how you framed it with a plan, and how the other person reacted.')
  on conflict (deck_slug, number) do update set category = excluded.category, question = excluded.question, hint = excluded.hint;
delete from public.cards where deck_slug = 'behavioral' and number > 15;

insert into public.decks (slug, name, short_name, tagline, color, is_free, sort) values ('software-engineering', 'Software Engineering Deck', 'Software Eng.', 'Tech roles', 'software-engineering', false, 2)
  on conflict (slug) do update set name = excluded.name, short_name = excluded.short_name, tagline = excluded.tagline, color = excluded.color, is_free = excluded.is_free, sort = excluded.sort;

insert into public.cards (deck_slug, number, category, question, hint) values
  ('software-engineering', 1, 'Technical depth', 'Tell me about the most complex system you have worked on.', 'Draw the big picture first (components, scale), then zoom into the part you owned and one hard decision you made.'),
  ('software-engineering', 2, 'Technical depth', 'Describe a hard bug you tracked down.', 'Walk through your debugging process: hypotheses, how you narrowed it down, the root cause and the fix that prevented repeats.'),
  ('software-engineering', 3, 'Trade-offs', 'Tell me about a technical decision you would make differently today.', 'Explain the constraints at the time, what you learned since, and what you would choose now and why.'),
  ('software-engineering', 4, 'Trade-offs', 'How do you balance shipping fast with code quality?', 'Give a concrete example of where you drew the line and how you paid back the debt later.'),
  ('software-engineering', 5, 'Collaboration', 'Tell me about a time you disagreed with a code review.', 'Show that you sought to understand the reviewer''s concern and resolved it with data or a quick experiment.'),
  ('software-engineering', 6, 'Collaboration', 'How do you work with product managers and designers?', 'Mention how you get involved early, push back on scope with alternatives, and keep them updated.'),
  ('software-engineering', 7, 'Ownership', 'Tell me about a production incident you handled.', 'Cover detection, mitigation, communication during the incident, and the postmortem actions.'),
  ('software-engineering', 8, 'Ownership', 'Describe a time you improved a process for your team.', 'Explain the pain, the change you proposed, how you got buy-in, and a metric that improved.'),
  ('software-engineering', 9, 'Growth', 'How do you keep your technical skills up to date?', 'Give specific habits and one recent example of something you learned and applied at work.'),
  ('software-engineering', 10, 'Growth', 'Tell me about a time you mentored another engineer.', 'Describe how you adapted to their level and how you know they grew.'),
  ('software-engineering', 11, 'System design', 'How would you explain your current system''s architecture to a new hire?', 'Start from the user request and follow it through the system. Mention the main trade-offs, not every service.'),
  ('software-engineering', 12, 'Career', 'Why do you want to work remotely for an international company?', 'Talk about the work and the team, show you have remote habits (async writing, overlap hours) that make it work.')
  on conflict (deck_slug, number) do update set category = excluded.category, question = excluded.question, hint = excluded.hint;
delete from public.cards where deck_slug = 'software-engineering' and number > 12;

insert into public.decks (slug, name, short_name, tagline, color, is_free, sort) values ('product', 'Product Management Deck', 'Product', 'Tech roles', 'product', false, 3)
  on conflict (slug) do update set name = excluded.name, short_name = excluded.short_name, tagline = excluded.tagline, color = excluded.color, is_free = excluded.is_free, sort = excluded.sort;

insert into public.cards (deck_slug, number, category, question, hint) values
  ('product', 1, 'Product sense', 'What is your favorite product and how would you improve it?', 'Pick a user segment, name one real problem they have, and propose a change with how you would measure success.'),
  ('product', 2, 'Product sense', 'Tell me about a product you launched from zero.', 'Cover the problem discovery, how you defined the MVP, launch, and what the data showed afterwards.'),
  ('product', 3, 'Prioritization', 'How do you decide what goes into the roadmap?', 'Explain your framework with a real example, including something important you chose not to do.'),
  ('product', 4, 'Prioritization', 'Tell me about a time you had to cut scope.', 'Show how you identified the must-haves and aligned stakeholders on the trade-off.'),
  ('product', 5, 'Metrics', 'How do you measure the success of a feature?', 'Name a primary metric tied to user value, guardrail metrics, and when you would call it a failure.'),
  ('product', 6, 'Metrics', 'Tell me about a time data changed your mind.', 'Explain what you believed, what the data showed, and the decision that followed.'),
  ('product', 7, 'Stakeholders', 'Describe a time you aligned teams with conflicting goals.', 'Show how you found the shared goal and made the trade-offs explicit.'),
  ('product', 8, 'Stakeholders', 'How do you work with engineering when estimates slip?', 'Talk about transparency, re-scoping options and protecting the team''s trust.'),
  ('product', 9, 'Users', 'How do you talk to users?', 'Describe your research habits and one insight that changed a product decision.'),
  ('product', 10, 'Users', 'Tell me about a time you had to say no to a big customer.', 'Explain how you weighed their request against the strategy and how you kept the relationship.'),
  ('product', 11, 'Strategy', 'How would you grow our product in a new market?', 'Start with the user and market differences, propose a small experiment, and define what success looks like.'),
  ('product', 12, 'Leadership', 'How do you lead without authority?', 'Give an example where you used context, data and trust to get people to move.')
  on conflict (deck_slug, number) do update set category = excluded.category, question = excluded.question, hint = excluded.hint;
delete from public.cards where deck_slug = 'product' and number > 12;
