import { readdirSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { z } from 'zod'
import { deckColorSchema } from '../shared/schemas/deck'

export const deckFileSchema = z.object({
  slug: z.string().regex(/^[a-z0-9-]+$/),
  name: z.string().min(1),
  shortName: z.string().min(1),
  tagline: z.string(),
  color: deckColorSchema,
  isFree: z.boolean(),
  sort: z.number().int(),
  cards: z.array(z.object({
    category: z.string().min(1),
    question: z.string().min(1),
    hint: z.string().min(1).nullable(),
  })).min(1),
}).strict()

export type DeckFile = z.infer<typeof deckFileSchema>

export function loadDeckFiles(dir: string): DeckFile[] {
  return readdirSync(dir)
    .filter(file => file.endsWith('.json'))
    .sort()
    .map((file) => {
      const parsed = deckFileSchema.safeParse(JSON.parse(readFileSync(join(dir, file), 'utf8')))
      if (!parsed.success) throw new Error(`${file}: ${z.prettifyError(parsed.error)}`)
      return parsed.data
    })
    .sort((a, b) => a.sort - b.sort)
}

const literal = (value: string | null) => (value === null ? 'null' : `'${value.replaceAll('\'', '\'\'')}'`)

/** Idempotent SQL: upserts decks and cards by (deck_slug, number), keeping card ids stable. */
export function toSeedSql(decks: DeckFile[]): string {
  const lines = ['-- Generated by scripts/build-seed.ts from supabase/seed/decks/*.json. Do not edit.', '']
  for (const deck of decks) {
    lines.push(
      `insert into public.decks (slug, name, short_name, tagline, color, is_free, sort) values (${[
        literal(deck.slug), literal(deck.name), literal(deck.shortName), literal(deck.tagline),
        literal(deck.color), String(deck.isFree), String(deck.sort),
      ].join(', ')})`,
      '  on conflict (slug) do update set name = excluded.name, short_name = excluded.short_name, tagline = excluded.tagline, color = excluded.color, is_free = excluded.is_free, sort = excluded.sort;',
      '',
      'insert into public.cards (deck_slug, number, category, question, hint) values',
      deck.cards.map((card, index) =>
        `  (${[literal(deck.slug), String(index + 1), literal(card.category), literal(card.question), literal(card.hint)].join(', ')})`,
      ).join(',\n'),
      '  on conflict (deck_slug, number) do update set category = excluded.category, question = excluded.question, hint = excluded.hint;',
      `delete from public.cards where deck_slug = ${literal(deck.slug)} and number > ${deck.cards.length};`,
      '',
    )
  }
  return lines.join('\n')
}
